# Generated by Django 5.0.3 on 2024-03-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yourmodel',
            name='file',
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='photo',
            field=models.FileField(default='photos/OIP.jpg', upload_to='photos/'),
        ),
    ]
