# Generated by Django 5.0.3 on 2024-03-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_yourmodel_file_yourmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourmodel',
            name='photo',
            field=models.ImageField(default='OIP.jpg', upload_to=''),
        ),
    ]
