# Generated by Django 5.0.3 on 2024-03-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_yourmodel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodel',
            name='link',
            field=models.URLField(default='index'),
        ),
    ]
